<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MAVLT1168" ignored="1" name="TestNG_Group" tests="3" failures="3" timestamp="2020-06-26T01:46:05 IST" time="0.016" errors="0">
  <testcase name="add_Group" time="0.0" classname="testng_assignment.TestNG_Groups">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.maveric.core.testng.listeners.DriverListener.beforeInvocation(DriverListener.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- add_Group -->
  <testcase name="sub_Group" time="0.001" classname="testng_assignment.TestNG_Groups">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.maveric.core.testng.listeners.DriverListener.beforeInvocation(DriverListener.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- sub_Group -->
  <testcase name="negate_Group" time="0.001" classname="testng_assignment.TestNG_Groups">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.maveric.core.testng.listeners.DriverListener.beforeInvocation(DriverListener.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- negate_Group -->
  <testcase name="inverse_Group" time="0.0" classname="testng_assignment.TestNG_Groups">
    <ignored/>
  </testcase> <!-- inverse_Group -->
</testsuite> <!-- TestNG_Group -->
